[package]
name = "ever-struct"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["EverX Labs <hello@everx.dev>"]
repository = "https://github.com/tonlabs/ever-struct"
rust-version = "1.65"
license = "Apache-2.0"

[dependencies]
failure = '0.1.0'
hex-literal = "0.3.4"
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block.git', tag = '1.9.22' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types.git', tag = '1.12.6' }
